// Code generated by "stringer -type=TxType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Update-0]
	_ = x[Lock-1]
	_ = x[Redeem-2]
}

const _TxType_name = "UpdateLockRedeem"

var _TxType_index = [...]uint8{0, 6, 10, 16}

func (i TxType) String() string {
	if i < 0 || i >= TxType(len(_TxType_index)-1) {
		return "TxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TxType_name[_TxType_index[i]:_TxType_index[i+1]]
}
