[dev]
selfbroadcastip = "127.0.0.1"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
syncdbpath = "./herdius/syncdb"
blockdbpath = "./herdius/blockdb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io/v3/"
blockchaininforpc = "https://blockchain.info/rawaddr/"
hercontractaddress = "0x7562157d0bbb6d78935133bf06ae279e707aa9ad"
s3backupbucket = "herdius-blockchain-backup-dev"
htokenrpc = "http://100.26.52.191:81/contract/%s"
tezosrpc = "http://172.105.158.208:9000"
checkerbtcurl = "https://blockchain.info/latestblock"
ltcrpc = "https://block.io/api/v2"
bnbrpc = "https://testnet-dex.binance.org/api/v1/account"
balanceapi = "http://ec2-54-193-67-5.us-west-1.compute.amazonaws.com/balance/"

[staging]
selfbroadcastip = "10.0.1.159"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
syncdbpath = "./herdius/syncdb"
blockdbpath = "./herdius/blockdb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "http://10.0.1.199:8545"
blockchaininforpc = "https://blockchain.info/rawaddr/"
hercontractaddress = "0x7562157d0bbb6d78935133bf06ae279e707aa9ad"
s3backupbucket = "herdius-blockchain-backup-staging"
htokenrpc = "http://100.26.52.191:81/contract/%s"
tezosrpc = "http://172.105.158.208:9000"
checkerbtcurl = "https://blockchain.info/latestblock"
ltcrpc = "https://block.io/api/v2"
bnbrpc = "https://testnet-dex.binance.org/api/v1/account"

[prod]
selfbroadcastip = "not supported"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
syncdbpath = "./herdius/syncdb"
statedbpath = "./herdius/statedb"
blockdbpath = "./herdius/blockdb"
badgerdb = "badger"
leveldb = "goleveldb"
ethrpc = "https://mainnet.infura.io/v3/"
blockchaininforpc = "https://blockchain.info/q"
s3backupbucket = "herdius-blockchain-backup-prod"
htokenrpc = "http://100.26.52.191:81/contract/%s"
tezosrpc = "http://172.105.158.208:9000"
checkerbtcurl = "https://blockchain.info/latestblock"
ltcrpc = "https://block.io/api/v2"
bnbrpc = "https://testnet-dex.binance.org/api/v1/account"
