// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/protobuf/stream.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Address              string                       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            string                       `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Nonce                uint64                       `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance              uint64                       `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	StorageRoot          string                       `protobuf:"bytes,5,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	Erc20Address         string                       `protobuf:"bytes,6,opt,name=erc20_address,json=erc20Address,proto3" json:"erc20_address,omitempty"`
	ExternalNonce        uint64                       `protobuf:"varint,7,opt,name=external_nonce,json=externalNonce,proto3" json:"external_nonce,omitempty"`
	LastBlockHeight      uint64                       `protobuf:"varint,8,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	EBalances            map[string]*EBalanceAsset    `protobuf:"bytes,9,rep,name=eBalances,proto3" json:"eBalances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LockBalances         map[string]*LockBalanceAsset `protobuf:"bytes,10,rep,name=lockBalances,proto3" json:"lockBalances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RedeemAddresses      map[string]*RedeemAddress    `protobuf:"bytes,11,rep,name=redeemAddresses,proto3" json:"redeemAddresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FirstExternalAddress map[string]string            `protobuf:"bytes,12,rep,name=FirstExternalAddress,proto3" json:"FirstExternalAddress,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetStorageRoot() string {
	if m != nil {
		return m.StorageRoot
	}
	return ""
}

func (m *Account) GetErc20Address() string {
	if m != nil {
		return m.Erc20Address
	}
	return ""
}

func (m *Account) GetExternalNonce() uint64 {
	if m != nil {
		return m.ExternalNonce
	}
	return 0
}

func (m *Account) GetLastBlockHeight() uint64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *Account) GetEBalances() map[string]*EBalanceAsset {
	if m != nil {
		return m.EBalances
	}
	return nil
}

func (m *Account) GetLockBalances() map[string]*LockBalanceAsset {
	if m != nil {
		return m.LockBalances
	}
	return nil
}

func (m *Account) GetRedeemAddresses() map[string]*RedeemAddress {
	if m != nil {
		return m.RedeemAddresses
	}
	return nil
}

func (m *Account) GetFirstExternalAddress() map[string]string {
	if m != nil {
		return m.FirstExternalAddress
	}
	return nil
}

type AccountRegisterRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRegisterRequest) Reset()         { *m = AccountRegisterRequest{} }
func (m *AccountRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRegisterRequest) ProtoMessage()    {}
func (*AccountRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{1}
}
func (m *AccountRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegisterRequest.Unmarshal(m, b)
}
func (m *AccountRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *AccountRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegisterRequest.Merge(dst, src)
}
func (m *AccountRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRegisterRequest.Size(m)
}
func (m *AccountRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegisterRequest proto.InternalMessageInfo

func (m *AccountRegisterRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type EBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LastBlockHeight      uint64   `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EBalance) Reset()         { *m = EBalance{} }
func (m *EBalance) String() string { return proto.CompactTextString(m) }
func (*EBalance) ProtoMessage()    {}
func (*EBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{2}
}
func (m *EBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBalance.Unmarshal(m, b)
}
func (m *EBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBalance.Marshal(b, m, deterministic)
}
func (dst *EBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBalance.Merge(dst, src)
}
func (m *EBalance) XXX_Size() int {
	return xxx_messageInfo_EBalance.Size(m)
}
func (m *EBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_EBalance.DiscardUnknown(m)
}

var xxx_messageInfo_EBalance proto.InternalMessageInfo

func (m *EBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *EBalance) GetLastBlockHeight() uint64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *EBalance) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type EBalanceAsset struct {
	Asset                map[string]*EBalance `protobuf:"bytes,1,rep,name=asset,proto3" json:"asset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EBalanceAsset) Reset()         { *m = EBalanceAsset{} }
func (m *EBalanceAsset) String() string { return proto.CompactTextString(m) }
func (*EBalanceAsset) ProtoMessage()    {}
func (*EBalanceAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{3}
}
func (m *EBalanceAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBalanceAsset.Unmarshal(m, b)
}
func (m *EBalanceAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBalanceAsset.Marshal(b, m, deterministic)
}
func (dst *EBalanceAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBalanceAsset.Merge(dst, src)
}
func (m *EBalanceAsset) XXX_Size() int {
	return xxx_messageInfo_EBalanceAsset.Size(m)
}
func (m *EBalanceAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_EBalanceAsset.DiscardUnknown(m)
}

var xxx_messageInfo_EBalanceAsset proto.InternalMessageInfo

func (m *EBalanceAsset) GetAsset() map[string]*EBalance {
	if m != nil {
		return m.Asset
	}
	return nil
}

type LockBalanceAsset struct {
	Asset                map[string]uint64 `protobuf:"bytes,1,rep,name=asset,proto3" json:"asset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LockBalanceAsset) Reset()         { *m = LockBalanceAsset{} }
func (m *LockBalanceAsset) String() string { return proto.CompactTextString(m) }
func (*LockBalanceAsset) ProtoMessage()    {}
func (*LockBalanceAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{4}
}
func (m *LockBalanceAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockBalanceAsset.Unmarshal(m, b)
}
func (m *LockBalanceAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockBalanceAsset.Marshal(b, m, deterministic)
}
func (dst *LockBalanceAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockBalanceAsset.Merge(dst, src)
}
func (m *LockBalanceAsset) XXX_Size() int {
	return xxx_messageInfo_LockBalanceAsset.Size(m)
}
func (m *LockBalanceAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_LockBalanceAsset.DiscardUnknown(m)
}

var xxx_messageInfo_LockBalanceAsset proto.InternalMessageInfo

func (m *LockBalanceAsset) GetAsset() map[string]uint64 {
	if m != nil {
		return m.Asset
	}
	return nil
}

type RedeemAddress struct {
	Address              map[string]string `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RedeemAddress) Reset()         { *m = RedeemAddress{} }
func (m *RedeemAddress) String() string { return proto.CompactTextString(m) }
func (*RedeemAddress) ProtoMessage()    {}
func (*RedeemAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_68ea89e55c9eaf05, []int{5}
}
func (m *RedeemAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemAddress.Unmarshal(m, b)
}
func (m *RedeemAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemAddress.Marshal(b, m, deterministic)
}
func (dst *RedeemAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemAddress.Merge(dst, src)
}
func (m *RedeemAddress) XXX_Size() int {
	return xxx_messageInfo_RedeemAddress.Size(m)
}
func (m *RedeemAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemAddress.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemAddress proto.InternalMessageInfo

func (m *RedeemAddress) GetAddress() map[string]string {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "protobuf.Account")
	proto.RegisterMapType((map[string]*EBalanceAsset)(nil), "protobuf.Account.EBalancesEntry")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.Account.FirstExternalAddressEntry")
	proto.RegisterMapType((map[string]*LockBalanceAsset)(nil), "protobuf.Account.LockBalancesEntry")
	proto.RegisterMapType((map[string]*RedeemAddress)(nil), "protobuf.Account.RedeemAddressesEntry")
	proto.RegisterType((*AccountRegisterRequest)(nil), "protobuf.AccountRegisterRequest")
	proto.RegisterType((*EBalance)(nil), "protobuf.EBalance")
	proto.RegisterType((*EBalanceAsset)(nil), "protobuf.EBalanceAsset")
	proto.RegisterMapType((map[string]*EBalance)(nil), "protobuf.EBalanceAsset.AssetEntry")
	proto.RegisterType((*LockBalanceAsset)(nil), "protobuf.LockBalanceAsset")
	proto.RegisterMapType((map[string]uint64)(nil), "protobuf.LockBalanceAsset.AssetEntry")
	proto.RegisterType((*RedeemAddress)(nil), "protobuf.RedeemAddress")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.RedeemAddress.AddressEntry")
}

func init() {
	proto.RegisterFile("accounts/protobuf/stream.proto", fileDescriptor_stream_68ea89e55c9eaf05)
}

var fileDescriptor_stream_68ea89e55c9eaf05 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x8f, 0xd2, 0x40,
	0x10, 0xc7, 0x53, 0x7e, 0x1c, 0x30, 0x94, 0xbb, 0x63, 0x43, 0xb4, 0x92, 0x68, 0x10, 0x3c, 0x43,
	0x34, 0xf6, 0x2e, 0xf8, 0x20, 0x39, 0x93, 0x4b, 0x20, 0xc1, 0xbb, 0xc4, 0x8b, 0x21, 0x4d, 0x7c,
	0xf2, 0xa1, 0x29, 0x65, 0x04, 0x72, 0x85, 0x3d, 0x77, 0xb7, 0x46, 0xde, 0x7c, 0x35, 0xfe, 0x01,
	0xfe, 0x01, 0xfe, 0xa3, 0xa6, 0xbb, 0xed, 0xd1, 0x85, 0xa2, 0xf1, 0x5e, 0x48, 0x67, 0x3a, 0xf3,
	0xd9, 0x2f, 0xb3, 0xdf, 0x29, 0x3c, 0xf1, 0x7c, 0x9f, 0x86, 0x2b, 0xc1, 0x4f, 0x6f, 0x19, 0x15,
	0x74, 0x12, 0x7e, 0x3e, 0xe5, 0x82, 0xa1, 0xb7, 0xb4, 0x65, 0x4c, 0xca, 0x49, 0xba, 0xfd, 0xbb,
	0x04, 0xa5, 0x81, 0x2a, 0x26, 0x16, 0x94, 0xbc, 0xe9, 0x94, 0x21, 0xe7, 0x96, 0xd1, 0x32, 0xba,
	0x15, 0x27, 0x09, 0xc9, 0x63, 0x80, 0xdb, 0x70, 0x12, 0x2c, 0x7c, 0xf7, 0x06, 0xd7, 0x56, 0x4e,
	0xbe, 0xac, 0xa8, 0xcc, 0x7b, 0x5c, 0x93, 0x06, 0x14, 0x57, 0x74, 0xe5, 0xa3, 0x95, 0x6f, 0x19,
	0xdd, 0x82, 0xa3, 0x82, 0x08, 0x37, 0xf1, 0x02, 0x2f, 0xca, 0x17, 0x64, 0x3e, 0x09, 0xc9, 0x53,
	0x30, 0xb9, 0xa0, 0xcc, 0x9b, 0xa1, 0xcb, 0x28, 0x15, 0x56, 0x51, 0x02, 0xab, 0x71, 0xce, 0xa1,
	0x54, 0x90, 0x0e, 0xd4, 0x90, 0xf9, 0xbd, 0x33, 0x37, 0x51, 0x74, 0x20, 0x6b, 0x4c, 0x99, 0x1c,
	0xc4, 0xb2, 0x4e, 0xe0, 0x10, 0xbf, 0x09, 0x64, 0x2b, 0x2f, 0x70, 0x95, 0x80, 0x92, 0x3c, 0xa8,
	0x96, 0x64, 0x3f, 0x48, 0x21, 0x2f, 0xa0, 0x1e, 0x78, 0x5c, 0xb8, 0x93, 0x80, 0xfa, 0x37, 0xee,
	0x1c, 0x17, 0xb3, 0xb9, 0xb0, 0xca, 0xb2, 0xf2, 0x28, 0x7a, 0x31, 0x8c, 0xf2, 0x57, 0x32, 0x4d,
	0x2e, 0xa0, 0x82, 0x43, 0x25, 0x93, 0x5b, 0x95, 0x56, 0xbe, 0x5b, 0xed, 0xb5, 0xec, 0x64, 0x5a,
	0x76, 0x3c, 0x29, 0x7b, 0x94, 0x94, 0x8c, 0x56, 0x82, 0xad, 0x9d, 0x4d, 0x0b, 0xb9, 0x04, 0x33,
	0xa2, 0xdd, 0x21, 0x40, 0x22, 0x3a, 0xbb, 0x88, 0xeb, 0x54, 0x95, 0xa2, 0x68, 0x8d, 0x64, 0x0c,
	0x47, 0x0c, 0xa7, 0x88, 0xcb, 0xf8, 0xcf, 0x22, 0xb7, 0xaa, 0x92, 0xf5, 0x7c, 0x97, 0xe5, 0xe8,
	0x85, 0x0a, 0xb7, 0xdd, 0x4e, 0x5c, 0x68, 0xbc, 0x5b, 0x30, 0x2e, 0x46, 0xf1, 0x70, 0xe2, 0x37,
	0x96, 0x29, 0xb1, 0x2f, 0x77, 0xb1, 0x59, 0xd5, 0x8a, 0x9d, 0x09, 0x6a, 0x7e, 0x84, 0x43, 0x7d,
	0x30, 0xe4, 0x18, 0xf2, 0x91, 0x61, 0x94, 0x9b, 0xa2, 0x47, 0xf2, 0x0a, 0x8a, 0x5f, 0xbd, 0x20,
	0x44, 0x69, 0xa2, 0x6a, 0xef, 0xe1, 0xe6, 0xd4, 0xa4, 0x75, 0xc0, 0x39, 0x0a, 0x47, 0x55, 0x9d,
	0xe7, 0xfa, 0x46, 0xf3, 0x13, 0xd4, 0x77, 0x86, 0x95, 0x41, 0x3e, 0xd3, 0xc9, 0xcd, 0x0d, 0x39,
	0xd5, 0x9d, 0x01, 0x6f, 0x64, 0x4d, 0xef, 0xbf, 0x94, 0x6b, 0x80, 0x34, 0xfc, 0x12, 0x1e, 0xed,
	0x9d, 0x61, 0xc6, 0x09, 0x8d, 0xf4, 0x09, 0x95, 0x14, 0xa8, 0xfd, 0x06, 0x1e, 0xc4, 0x97, 0xe2,
	0xe0, 0x6c, 0xc1, 0x05, 0x32, 0x07, 0xbf, 0x84, 0xc8, 0xc5, 0xd6, 0x66, 0x1a, 0x5b, 0x9b, 0xd9,
	0xfe, 0x6e, 0x40, 0x39, 0x19, 0xec, 0x5f, 0xf6, 0x3b, 0xb5, 0xaa, 0x39, 0x7d, 0x55, 0x33, 0x77,
	0x27, 0x9f, 0xbd, 0x3b, 0x77, 0x9f, 0x81, 0x42, 0xea, 0x33, 0xd0, 0xfe, 0x65, 0x40, 0x4d, 0xbb,
	0x5b, 0xd2, 0x87, 0xa2, 0x17, 0x3d, 0x58, 0x86, 0x74, 0x5e, 0x7b, 0x8f, 0x07, 0x6c, 0xf9, 0xab,
	0x0c, 0xa7, 0x1a, 0x9a, 0xd7, 0x00, 0x9b, 0x64, 0xc6, 0x04, 0xbb, 0xfa, 0x1d, 0x91, 0x5d, 0x72,
	0x7a, 0xaa, 0x3f, 0x0c, 0x38, 0xde, 0xf6, 0x06, 0x79, 0xab, 0x8b, 0x3b, 0xd9, 0x6f, 0xa3, 0x0c,
	0x7d, 0xfd, 0x7f, 0xe8, 0xd3, 0x6e, 0xb8, 0x90, 0xd6, 0xf2, 0xd3, 0x80, 0x9a, 0xe6, 0x23, 0x72,
	0x91, 0xbe, 0xad, 0x48, 0xca, 0xb3, 0x3d, 0x8e, 0xb3, 0xb5, 0xd5, 0x4c, 0x9a, 0x9a, 0xe7, 0x60,
	0xde, 0xd7, 0x6f, 0xc3, 0x0e, 0xd4, 0x7d, 0xba, 0xb4, 0xe7, 0xc8, 0xa6, 0x8b, 0x90, 0xab, 0x73,
	0x87, 0xe6, 0x95, 0x0a, 0xc7, 0x51, 0x34, 0x36, 0x26, 0x07, 0x32, 0xfd, 0xfa, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5d, 0x41, 0xfe, 0x78, 0x6d, 0x06, 0x00, 0x00,
}
