// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hbi/protobuf/service.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int64    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (dst *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(dst, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type BlockHeightRequest struct {
	BlockHeight          int64    `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeightRequest) Reset()         { *m = BlockHeightRequest{} }
func (m *BlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*BlockHeightRequest) ProtoMessage()    {}
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{1}
}
func (m *BlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeightRequest.Unmarshal(m, b)
}
func (m *BlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeightRequest.Marshal(b, m, deterministic)
}
func (dst *BlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeightRequest.Merge(dst, src)
}
func (m *BlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_BlockHeightRequest.Size(m)
}
func (m *BlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeightRequest proto.InternalMessageInfo

func (m *BlockHeightRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type BlockResponse struct {
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Time of block intialization
	Time     *Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TotalTxs uint64     `protobuf:"varint,3,opt,name=total_txs,json=totalTxs,proto3" json:"total_txs,omitempty"`
	// Supervisor herdius token address who created the block
	SupervisorAddress    string   `protobuf:"bytes,4,opt,name=supervisor_address,json=supervisorAddress,proto3" json:"supervisor_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{2}
}
func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (dst *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(dst, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockResponse) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BlockResponse) GetTotalTxs() uint64 {
	if m != nil {
		return m.TotalTxs
	}
	return 0
}

func (m *BlockResponse) GetSupervisorAddress() string {
	if m != nil {
		return m.SupervisorAddress
	}
	return ""
}

type AccountRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{3}
}
func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (dst *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(dst, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AccountResponse struct {
	Address              string                    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce                uint64                    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	StorageRoot          string                    `protobuf:"bytes,3,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	PublicKey            string                    `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Balance              uint64                    `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Erc20Address         string                    `protobuf:"bytes,6,opt,name=erc20_address,json=erc20Address,proto3" json:"erc20_address,omitempty"`
	ExternalNonce        uint64                    `protobuf:"varint,7,opt,name=external_nonce,json=externalNonce,proto3" json:"external_nonce,omitempty"`
	LastBlockHeight      uint64                    `protobuf:"varint,8,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	EBalances            map[string]*EBalanceAsset `protobuf:"bytes,9,rep,name=eBalances,proto3" json:"eBalances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FirstExternalAddress map[string]string         `protobuf:"bytes,10,rep,name=FirstExternalAddress,proto3" json:"FirstExternalAddress,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{4}
}
func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (dst *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(dst, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *AccountResponse) GetStorageRoot() string {
	if m != nil {
		return m.StorageRoot
	}
	return ""
}

func (m *AccountResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *AccountResponse) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AccountResponse) GetErc20Address() string {
	if m != nil {
		return m.Erc20Address
	}
	return ""
}

func (m *AccountResponse) GetExternalNonce() uint64 {
	if m != nil {
		return m.ExternalNonce
	}
	return 0
}

func (m *AccountResponse) GetLastBlockHeight() uint64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *AccountResponse) GetEBalances() map[string]*EBalanceAsset {
	if m != nil {
		return m.EBalances
	}
	return nil
}

func (m *AccountResponse) GetFirstExternalAddress() map[string]string {
	if m != nil {
		return m.FirstExternalAddress
	}
	return nil
}

type Asset struct {
	Category                string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Symbol                  string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Network                 string   `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Value                   uint64   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Fee                     uint64   `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Nonce                   uint64   `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExternalSenderAddress   string   `protobuf:"bytes,7,opt,name=external_sender_address,json=externalSenderAddress,proto3" json:"external_sender_address,omitempty"`
	ExternalRecieverAddress string   `protobuf:"bytes,8,opt,name=external_reciever_address,json=externalRecieverAddress,proto3" json:"external_reciever_address,omitempty"`
	ExternalNonce           uint64   `protobuf:"varint,9,opt,name=external_nonce,json=externalNonce,proto3" json:"external_nonce,omitempty"`
	ExternalBlockHeight     uint64   `protobuf:"varint,10,opt,name=external_block_height,json=externalBlockHeight,proto3" json:"external_block_height,omitempty"`
	LockedAmount            uint64   `protobuf:"varint,11,opt,name=locked_amount,json=lockedAmount,proto3" json:"locked_amount,omitempty"`
	RedeemedAmount          uint64   `protobuf:"varint,12,opt,name=redeemed_amount,json=redeemedAmount,proto3" json:"redeemed_amount,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{5}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (dst *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(dst, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Asset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Asset) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Asset) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Asset) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Asset) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Asset) GetExternalSenderAddress() string {
	if m != nil {
		return m.ExternalSenderAddress
	}
	return ""
}

func (m *Asset) GetExternalRecieverAddress() string {
	if m != nil {
		return m.ExternalRecieverAddress
	}
	return ""
}

func (m *Asset) GetExternalNonce() uint64 {
	if m != nil {
		return m.ExternalNonce
	}
	return 0
}

func (m *Asset) GetExternalBlockHeight() uint64 {
	if m != nil {
		return m.ExternalBlockHeight
	}
	return 0
}

func (m *Asset) GetLockedAmount() uint64 {
	if m != nil {
		return m.LockedAmount
	}
	return 0
}

func (m *Asset) GetRedeemedAmount() uint64 {
	if m != nil {
		return m.RedeemedAmount
	}
	return 0
}

type Tx struct {
	SenderAddress   string `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderPubkey    string `protobuf:"bytes,2,opt,name=sender_pubkey,json=senderPubkey,proto3" json:"sender_pubkey,omitempty"`
	RecieverAddress string `protobuf:"bytes,3,opt,name=reciever_address,json=recieverAddress,proto3" json:"reciever_address,omitempty"`
	Asset           *Asset `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Message         string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Sign            string `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	// type will check if tx is of type Account Registeration or Value Transfer
	Type   string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Status string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// For interacting with compound protocol
	Data                 string   `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{6}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *Tx) GetSenderPubkey() string {
	if m != nil {
		return m.SenderPubkey
	}
	return ""
}

func (m *Tx) GetRecieverAddress() string {
	if m != nil {
		return m.RecieverAddress
	}
	return ""
}

func (m *Tx) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *Tx) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Tx) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *Tx) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tx) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Tx) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type TxRequest struct {
	Tx                   *Tx      `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequest) Reset()         { *m = TxRequest{} }
func (m *TxRequest) String() string { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()    {}
func (*TxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{7}
}
func (m *TxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequest.Unmarshal(m, b)
}
func (m *TxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequest.Marshal(b, m, deterministic)
}
func (dst *TxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequest.Merge(dst, src)
}
func (m *TxRequest) XXX_Size() int {
	return xxx_messageInfo_TxRequest.Size(m)
}
func (m *TxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequest proto.InternalMessageInfo

func (m *TxRequest) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

type TxResponse struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Pending              int64    `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Queued               int64    `protobuf:"varint,3,opt,name=queued,proto3" json:"queued,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxResponse) Reset()         { *m = TxResponse{} }
func (m *TxResponse) String() string { return proto.CompactTextString(m) }
func (*TxResponse) ProtoMessage()    {}
func (*TxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{8}
}
func (m *TxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxResponse.Unmarshal(m, b)
}
func (m *TxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxResponse.Marshal(b, m, deterministic)
}
func (dst *TxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxResponse.Merge(dst, src)
}
func (m *TxResponse) XXX_Size() int {
	return xxx_messageInfo_TxResponse.Size(m)
}
func (m *TxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxResponse proto.InternalMessageInfo

func (m *TxResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxResponse) GetPending() int64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *TxResponse) GetQueued() int64 {
	if m != nil {
		return m.Queued
	}
	return 0
}

func (m *TxResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TxResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccountRegisterRequest struct {
	SenderPubkey         string   `protobuf:"bytes,1,opt,name=sender_pubkey,json=senderPubkey,proto3" json:"sender_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRegisterRequest) Reset()         { *m = AccountRegisterRequest{} }
func (m *AccountRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRegisterRequest) ProtoMessage()    {}
func (*AccountRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{9}
}
func (m *AccountRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegisterRequest.Unmarshal(m, b)
}
func (m *AccountRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *AccountRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegisterRequest.Merge(dst, src)
}
func (m *AccountRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRegisterRequest.Size(m)
}
func (m *AccountRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegisterRequest proto.InternalMessageInfo

func (m *AccountRegisterRequest) GetSenderPubkey() string {
	if m != nil {
		return m.SenderPubkey
	}
	return ""
}

// Send request to retrieve transaction committed in herdius blockchain
type TxDetailRequest struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxDetailRequest) Reset()         { *m = TxDetailRequest{} }
func (m *TxDetailRequest) String() string { return proto.CompactTextString(m) }
func (*TxDetailRequest) ProtoMessage()    {}
func (*TxDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{10}
}
func (m *TxDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDetailRequest.Unmarshal(m, b)
}
func (m *TxDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDetailRequest.Marshal(b, m, deterministic)
}
func (dst *TxDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDetailRequest.Merge(dst, src)
}
func (m *TxDetailRequest) XXX_Size() int {
	return xxx_messageInfo_TxDetailRequest.Size(m)
}
func (m *TxDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxDetailRequest proto.InternalMessageInfo

func (m *TxDetailRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// Transaction detail response from herdius blockchain
type TxDetailResponse struct {
	TxId                 string     `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Tx                   *Tx        `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	CreationDt           *Timestamp `protobuf:"bytes,3,opt,name=creationDt,proto3" json:"creationDt,omitempty"`
	BlockId              uint64     `protobuf:"varint,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TxDetailResponse) Reset()         { *m = TxDetailResponse{} }
func (m *TxDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TxDetailResponse) ProtoMessage()    {}
func (*TxDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{11}
}
func (m *TxDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDetailResponse.Unmarshal(m, b)
}
func (m *TxDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDetailResponse.Marshal(b, m, deterministic)
}
func (dst *TxDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDetailResponse.Merge(dst, src)
}
func (m *TxDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TxDetailResponse.Size(m)
}
func (m *TxDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxDetailResponse proto.InternalMessageInfo

func (m *TxDetailResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxDetailResponse) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *TxDetailResponse) GetCreationDt() *Timestamp {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

func (m *TxDetailResponse) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

type Transaction struct {
	Senderpubkey         []byte   `protobuf:"bytes,1,opt,name=senderpubkey,proto3" json:"senderpubkey,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Recaddress           string   `protobuf:"bytes,3,opt,name=recaddress,proto3" json:"recaddress,omitempty"`
	Asset                *Asset   `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{12}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSenderpubkey() []byte {
	if m != nil {
		return m.Senderpubkey
	}
	return nil
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetRecaddress() string {
	if m != nil {
		return m.Recaddress
	}
	return ""
}

func (m *Transaction) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type TransactionRequest struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=Tx,proto3" json:"Tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{13}
}
func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (dst *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(dst, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type TransactionResponse struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Pending              int64    `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Queued               int64    `protobuf:"varint,3,opt,name=queued,proto3" json:"queued,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{14}
}
func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (dst *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(dst, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TransactionResponse) GetPending() int64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *TransactionResponse) GetQueued() int64 {
	if m != nil {
		return m.Queued
	}
	return 0
}

func (m *TransactionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Send request to retrieve all transactions of an address committed in herdius blockchain
type TxsByAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsByAddressRequest) Reset()         { *m = TxsByAddressRequest{} }
func (m *TxsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*TxsByAddressRequest) ProtoMessage()    {}
func (*TxsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{15}
}
func (m *TxsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsByAddressRequest.Unmarshal(m, b)
}
func (m *TxsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsByAddressRequest.Marshal(b, m, deterministic)
}
func (dst *TxsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsByAddressRequest.Merge(dst, src)
}
func (m *TxsByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_TxsByAddressRequest.Size(m)
}
func (m *TxsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxsByAddressRequest proto.InternalMessageInfo

func (m *TxsByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Transactions details response from herdius blockchain
type TxsResponse struct {
	Txs                  []*TxDetailResponse `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxsResponse) Reset()         { *m = TxsResponse{} }
func (m *TxsResponse) String() string { return proto.CompactTextString(m) }
func (*TxsResponse) ProtoMessage()    {}
func (*TxsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{16}
}
func (m *TxsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsResponse.Unmarshal(m, b)
}
func (m *TxsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsResponse.Marshal(b, m, deterministic)
}
func (dst *TxsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsResponse.Merge(dst, src)
}
func (m *TxsResponse) XXX_Size() int {
	return xxx_messageInfo_TxsResponse.Size(m)
}
func (m *TxsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxsResponse proto.InternalMessageInfo

func (m *TxsResponse) GetTxs() []*TxDetailResponse {
	if m != nil {
		return m.Txs
	}
	return nil
}

// Send request to retrieve all transactions of an address and asset committed in herdius blockchain
type TxsByAssetAndAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsByAssetAndAddressRequest) Reset()         { *m = TxsByAssetAndAddressRequest{} }
func (m *TxsByAssetAndAddressRequest) String() string { return proto.CompactTextString(m) }
func (*TxsByAssetAndAddressRequest) ProtoMessage()    {}
func (*TxsByAssetAndAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{17}
}
func (m *TxsByAssetAndAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsByAssetAndAddressRequest.Unmarshal(m, b)
}
func (m *TxsByAssetAndAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsByAssetAndAddressRequest.Marshal(b, m, deterministic)
}
func (dst *TxsByAssetAndAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsByAssetAndAddressRequest.Merge(dst, src)
}
func (m *TxsByAssetAndAddressRequest) XXX_Size() int {
	return xxx_messageInfo_TxsByAssetAndAddressRequest.Size(m)
}
func (m *TxsByAssetAndAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsByAssetAndAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxsByAssetAndAddressRequest proto.InternalMessageInfo

func (m *TxsByAssetAndAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxsByAssetAndAddressRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

// TxCancelRequest contains the TX ID of the transaction in the MemPool to cancel
type TxUpdateRequest struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Tx                   *Tx      `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxUpdateRequest) Reset()         { *m = TxUpdateRequest{} }
func (m *TxUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*TxUpdateRequest) ProtoMessage()    {}
func (*TxUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{18}
}
func (m *TxUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxUpdateRequest.Unmarshal(m, b)
}
func (m *TxUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *TxUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxUpdateRequest.Merge(dst, src)
}
func (m *TxUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_TxUpdateRequest.Size(m)
}
func (m *TxUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxUpdateRequest proto.InternalMessageInfo

func (m *TxUpdateRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxUpdateRequest) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

// TxCancelResponse details status of cancellation request
type TxUpdateResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TxId                 string   `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Tx                   *Tx      `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxUpdateResponse) Reset()         { *m = TxUpdateResponse{} }
func (m *TxUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*TxUpdateResponse) ProtoMessage()    {}
func (*TxUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{19}
}
func (m *TxUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxUpdateResponse.Unmarshal(m, b)
}
func (m *TxUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *TxUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxUpdateResponse.Merge(dst, src)
}
func (m *TxUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_TxUpdateResponse.Size(m)
}
func (m *TxUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxUpdateResponse proto.InternalMessageInfo

func (m *TxUpdateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *TxUpdateResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxUpdateResponse) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *TxUpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LastBlockHeight      uint64   `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EBalance) Reset()         { *m = EBalance{} }
func (m *EBalance) String() string { return proto.CompactTextString(m) }
func (*EBalance) ProtoMessage()    {}
func (*EBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{20}
}
func (m *EBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBalance.Unmarshal(m, b)
}
func (m *EBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBalance.Marshal(b, m, deterministic)
}
func (dst *EBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBalance.Merge(dst, src)
}
func (m *EBalance) XXX_Size() int {
	return xxx_messageInfo_EBalance.Size(m)
}
func (m *EBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_EBalance.DiscardUnknown(m)
}

var xxx_messageInfo_EBalance proto.InternalMessageInfo

func (m *EBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *EBalance) GetLastBlockHeight() uint64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *EBalance) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type EBalanceAsset struct {
	Asset                map[string]*EBalance `protobuf:"bytes,1,rep,name=asset,proto3" json:"asset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EBalanceAsset) Reset()         { *m = EBalanceAsset{} }
func (m *EBalanceAsset) String() string { return proto.CompactTextString(m) }
func (*EBalanceAsset) ProtoMessage()    {}
func (*EBalanceAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{21}
}
func (m *EBalanceAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBalanceAsset.Unmarshal(m, b)
}
func (m *EBalanceAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBalanceAsset.Marshal(b, m, deterministic)
}
func (dst *EBalanceAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBalanceAsset.Merge(dst, src)
}
func (m *EBalanceAsset) XXX_Size() int {
	return xxx_messageInfo_EBalanceAsset.Size(m)
}
func (m *EBalanceAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_EBalanceAsset.DiscardUnknown(m)
}

var xxx_messageInfo_EBalanceAsset proto.InternalMessageInfo

func (m *EBalanceAsset) GetAsset() map[string]*EBalance {
	if m != nil {
		return m.Asset
	}
	return nil
}

type TxDeleteRequest struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxDeleteRequest) Reset()         { *m = TxDeleteRequest{} }
func (m *TxDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TxDeleteRequest) ProtoMessage()    {}
func (*TxDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{22}
}
func (m *TxDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDeleteRequest.Unmarshal(m, b)
}
func (m *TxDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *TxDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDeleteRequest.Merge(dst, src)
}
func (m *TxDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TxDeleteRequest.Size(m)
}
func (m *TxDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxDeleteRequest proto.InternalMessageInfo

func (m *TxDeleteRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

type TxLockedRequest struct {
	BlockNumber          int64    `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxLockedRequest) Reset()         { *m = TxLockedRequest{} }
func (m *TxLockedRequest) String() string { return proto.CompactTextString(m) }
func (*TxLockedRequest) ProtoMessage()    {}
func (*TxLockedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{23}
}
func (m *TxLockedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxLockedRequest.Unmarshal(m, b)
}
func (m *TxLockedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxLockedRequest.Marshal(b, m, deterministic)
}
func (dst *TxLockedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxLockedRequest.Merge(dst, src)
}
func (m *TxLockedRequest) XXX_Size() int {
	return xxx_messageInfo_TxLockedRequest.Size(m)
}
func (m *TxLockedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxLockedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxLockedRequest proto.InternalMessageInfo

func (m *TxLockedRequest) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type TxLockedResponse struct {
	Txs                  []*TxDetailResponse `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxLockedResponse) Reset()         { *m = TxLockedResponse{} }
func (m *TxLockedResponse) String() string { return proto.CompactTextString(m) }
func (*TxLockedResponse) ProtoMessage()    {}
func (*TxLockedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{24}
}
func (m *TxLockedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxLockedResponse.Unmarshal(m, b)
}
func (m *TxLockedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxLockedResponse.Marshal(b, m, deterministic)
}
func (dst *TxLockedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxLockedResponse.Merge(dst, src)
}
func (m *TxLockedResponse) XXX_Size() int {
	return xxx_messageInfo_TxLockedResponse.Size(m)
}
func (m *TxLockedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxLockedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxLockedResponse proto.InternalMessageInfo

func (m *TxLockedResponse) GetTxs() []*TxDetailResponse {
	if m != nil {
		return m.Txs
	}
	return nil
}

type TxRedeemRequest struct {
	BlockNumber          int64    `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRedeemRequest) Reset()         { *m = TxRedeemRequest{} }
func (m *TxRedeemRequest) String() string { return proto.CompactTextString(m) }
func (*TxRedeemRequest) ProtoMessage()    {}
func (*TxRedeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{25}
}
func (m *TxRedeemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRedeemRequest.Unmarshal(m, b)
}
func (m *TxRedeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRedeemRequest.Marshal(b, m, deterministic)
}
func (dst *TxRedeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRedeemRequest.Merge(dst, src)
}
func (m *TxRedeemRequest) XXX_Size() int {
	return xxx_messageInfo_TxRedeemRequest.Size(m)
}
func (m *TxRedeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRedeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxRedeemRequest proto.InternalMessageInfo

func (m *TxRedeemRequest) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type TxRedeemResponse struct {
	Txs                  []*TxDetailResponse `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxRedeemResponse) Reset()         { *m = TxRedeemResponse{} }
func (m *TxRedeemResponse) String() string { return proto.CompactTextString(m) }
func (*TxRedeemResponse) ProtoMessage()    {}
func (*TxRedeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{26}
}
func (m *TxRedeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRedeemResponse.Unmarshal(m, b)
}
func (m *TxRedeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRedeemResponse.Marshal(b, m, deterministic)
}
func (dst *TxRedeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRedeemResponse.Merge(dst, src)
}
func (m *TxRedeemResponse) XXX_Size() int {
	return xxx_messageInfo_TxRedeemResponse.Size(m)
}
func (m *TxRedeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRedeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxRedeemResponse proto.InternalMessageInfo

func (m *TxRedeemResponse) GetTxs() []*TxDetailResponse {
	if m != nil {
		return m.Txs
	}
	return nil
}

type TxsByBlockHeightRequest struct {
	BlockHeight          int64    `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsByBlockHeightRequest) Reset()         { *m = TxsByBlockHeightRequest{} }
func (m *TxsByBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*TxsByBlockHeightRequest) ProtoMessage()    {}
func (*TxsByBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{27}
}
func (m *TxsByBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsByBlockHeightRequest.Unmarshal(m, b)
}
func (m *TxsByBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsByBlockHeightRequest.Marshal(b, m, deterministic)
}
func (dst *TxsByBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsByBlockHeightRequest.Merge(dst, src)
}
func (m *TxsByBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_TxsByBlockHeightRequest.Size(m)
}
func (m *TxsByBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsByBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxsByBlockHeightRequest proto.InternalMessageInfo

func (m *TxsByBlockHeightRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type LastBlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockRequest) Reset()         { *m = LastBlockRequest{} }
func (m *LastBlockRequest) String() string { return proto.CompactTextString(m) }
func (*LastBlockRequest) ProtoMessage()    {}
func (*LastBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ed004cba14c1b32f, []int{28}
}
func (m *LastBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockRequest.Unmarshal(m, b)
}
func (m *LastBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockRequest.Marshal(b, m, deterministic)
}
func (dst *LastBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockRequest.Merge(dst, src)
}
func (m *LastBlockRequest) XXX_Size() int {
	return xxx_messageInfo_LastBlockRequest.Size(m)
}
func (m *LastBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Timestamp)(nil), "protobuf.Timestamp")
	proto.RegisterType((*BlockHeightRequest)(nil), "protobuf.BlockHeightRequest")
	proto.RegisterType((*BlockResponse)(nil), "protobuf.BlockResponse")
	proto.RegisterType((*AccountRequest)(nil), "protobuf.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "protobuf.AccountResponse")
	proto.RegisterMapType((map[string]*EBalanceAsset)(nil), "protobuf.AccountResponse.EBalancesEntry")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.AccountResponse.FirstExternalAddressEntry")
	proto.RegisterType((*Asset)(nil), "protobuf.Asset")
	proto.RegisterType((*Tx)(nil), "protobuf.Tx")
	proto.RegisterType((*TxRequest)(nil), "protobuf.TxRequest")
	proto.RegisterType((*TxResponse)(nil), "protobuf.TxResponse")
	proto.RegisterType((*AccountRegisterRequest)(nil), "protobuf.AccountRegisterRequest")
	proto.RegisterType((*TxDetailRequest)(nil), "protobuf.TxDetailRequest")
	proto.RegisterType((*TxDetailResponse)(nil), "protobuf.TxDetailResponse")
	proto.RegisterType((*Transaction)(nil), "protobuf.Transaction")
	proto.RegisterType((*TransactionRequest)(nil), "protobuf.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "protobuf.TransactionResponse")
	proto.RegisterType((*TxsByAddressRequest)(nil), "protobuf.TxsByAddressRequest")
	proto.RegisterType((*TxsResponse)(nil), "protobuf.TxsResponse")
	proto.RegisterType((*TxsByAssetAndAddressRequest)(nil), "protobuf.TxsByAssetAndAddressRequest")
	proto.RegisterType((*TxUpdateRequest)(nil), "protobuf.TxUpdateRequest")
	proto.RegisterType((*TxUpdateResponse)(nil), "protobuf.TxUpdateResponse")
	proto.RegisterType((*EBalance)(nil), "protobuf.EBalance")
	proto.RegisterType((*EBalanceAsset)(nil), "protobuf.EBalanceAsset")
	proto.RegisterMapType((map[string]*EBalance)(nil), "protobuf.EBalanceAsset.AssetEntry")
	proto.RegisterType((*TxDeleteRequest)(nil), "protobuf.TxDeleteRequest")
	proto.RegisterType((*TxLockedRequest)(nil), "protobuf.TxLockedRequest")
	proto.RegisterType((*TxLockedResponse)(nil), "protobuf.TxLockedResponse")
	proto.RegisterType((*TxRedeemRequest)(nil), "protobuf.TxRedeemRequest")
	proto.RegisterType((*TxRedeemResponse)(nil), "protobuf.TxRedeemResponse")
	proto.RegisterType((*TxsByBlockHeightRequest)(nil), "protobuf.TxsByBlockHeightRequest")
	proto.RegisterType((*LastBlockRequest)(nil), "protobuf.LastBlockRequest")
}

func init() { proto.RegisterFile("hbi/protobuf/service.proto", fileDescriptor_service_ed004cba14c1b32f) }

var fileDescriptor_service_ed004cba14c1b32f = []byte{
	// 1242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0x07, 0xf5, 0xb0, 0xc5, 0x91, 0x64, 0x39, 0x6b, 0x27, 0x96, 0x95, 0xfc, 0xff, 0x70, 0xd7,
	0x48, 0xa3, 0x04, 0xb5, 0x5d, 0xc8, 0x45, 0x1b, 0xc4, 0x2d, 0x50, 0x1b, 0x76, 0x9a, 0xa0, 0x6e,
	0x60, 0xb0, 0xca, 0xa5, 0x17, 0x81, 0x22, 0x37, 0x32, 0x61, 0x89, 0x54, 0x76, 0x97, 0x2e, 0x75,
	0xeb, 0xa5, 0xf7, 0x5e, 0xda, 0x7e, 0x84, 0x5e, 0xfb, 0xa9, 0xfa, 0x39, 0x8a, 0x7d, 0xf1, 0x11,
	0x49, 0xae, 0xeb, 0x43, 0x6f, 0x9c, 0xd9, 0x79, 0xcf, 0x6f, 0x77, 0x86, 0xd0, 0xb9, 0x1c, 0x06,
	0x07, 0x53, 0x1a, 0xf1, 0x68, 0x18, 0xbf, 0x3b, 0x60, 0x84, 0x5e, 0x07, 0x1e, 0xd9, 0x97, 0x0c,
	0x54, 0x33, 0x7c, 0x7c, 0x04, 0x76, 0x3f, 0x98, 0x10, 0xc6, 0xdd, 0xc9, 0x14, 0xb5, 0x61, 0x95,
	0x11, 0x2f, 0x0a, 0x7d, 0xd6, 0xb6, 0x76, 0xac, 0x6e, 0xd9, 0x31, 0x24, 0xda, 0x84, 0x6a, 0xe8,
	0x86, 0x11, 0x6b, 0x97, 0x24, 0x5f, 0x11, 0xf8, 0x0b, 0x40, 0x27, 0xe3, 0xc8, 0xbb, 0x7a, 0x45,
	0x82, 0xd1, 0x25, 0x77, 0xc8, 0xfb, 0x98, 0x30, 0x8e, 0x3e, 0x82, 0xc6, 0x50, 0x70, 0x07, 0x97,
	0x92, 0xad, 0x4d, 0xd5, 0x87, 0x99, 0x24, 0xfe, 0xc3, 0x82, 0xa6, 0xd4, 0x74, 0x08, 0x9b, 0x46,
	0x21, 0x23, 0xb7, 0x50, 0x42, 0x4f, 0xa0, 0xc2, 0x83, 0x09, 0x91, 0x21, 0xd4, 0x7b, 0x1b, 0xfb,
	0x26, 0x87, 0xfd, 0x34, 0x01, 0x47, 0x0a, 0xa0, 0x87, 0x60, 0xf3, 0x88, 0xbb, 0xe3, 0x01, 0x4f,
	0x58, 0xbb, 0xbc, 0x63, 0x75, 0x2b, 0x4e, 0x4d, 0x32, 0xfa, 0x09, 0x43, 0x7b, 0x80, 0x58, 0x3c,
	0x15, 0xd5, 0x60, 0x11, 0x1d, 0xb8, 0xbe, 0x4f, 0x09, 0x63, 0xed, 0xca, 0x8e, 0xd5, 0xb5, 0x9d,
	0x7b, 0xd9, 0xc9, 0xb1, 0x3a, 0xc0, 0xcf, 0x60, 0xed, 0xd8, 0xf3, 0xa2, 0x38, 0x4c, 0xd3, 0x6b,
	0xc3, 0xaa, 0xd1, 0xb2, 0xa4, 0x96, 0x21, 0xf1, 0x5f, 0x15, 0x68, 0xa5, 0xc2, 0x3a, 0xaf, 0xa5,
	0xd2, 0xb2, 0xa4, 0x51, 0xe8, 0xa9, 0x7c, 0x2a, 0x8e, 0x22, 0x44, 0x1d, 0x18, 0x8f, 0xa8, 0x3b,
	0x22, 0x03, 0x1a, 0x45, 0x5c, 0x86, 0x6f, 0x3b, 0x75, 0xcd, 0x73, 0xa2, 0x88, 0xa3, 0xff, 0x01,
	0x4c, 0xe3, 0xe1, 0x38, 0xf0, 0x06, 0x57, 0x64, 0xa6, 0x23, 0xb7, 0x15, 0xe7, 0x5b, 0x32, 0x13,
	0x1e, 0x87, 0xee, 0xd8, 0x15, 0x96, 0xab, 0xd2, 0xb2, 0x21, 0xd1, 0x2e, 0x34, 0x09, 0xf5, 0x7a,
	0x9f, 0xa6, 0x59, 0xaf, 0x48, 0xdd, 0x86, 0x64, 0xea, 0x84, 0xd1, 0x63, 0x58, 0x23, 0x09, 0x27,
	0x34, 0x74, 0xc7, 0x03, 0x15, 0xdf, 0xaa, 0xb4, 0xd2, 0x34, 0xdc, 0x37, 0x32, 0xce, 0x67, 0x70,
	0x6f, 0xec, 0x32, 0x3e, 0x28, 0x34, 0xad, 0x26, 0x25, 0x5b, 0xe2, 0x20, 0x87, 0x0b, 0xf4, 0x12,
	0x6c, 0x72, 0xa2, 0x62, 0x60, 0x6d, 0x7b, 0xa7, 0xdc, 0xad, 0xf7, 0xba, 0x59, 0xf7, 0x3e, 0xa8,
	0xd8, 0xfe, 0x99, 0x11, 0x3d, 0x0b, 0x39, 0x9d, 0x39, 0x99, 0x2a, 0x1a, 0xc1, 0xe6, 0xcb, 0x80,
	0x32, 0x7e, 0xa6, 0x23, 0xd1, 0x21, 0xb7, 0x41, 0x9a, 0x3c, 0x5c, 0x6e, 0x72, 0x91, 0x96, 0xb2,
	0xbe, 0xd0, 0x60, 0xe7, 0x2d, 0xac, 0x15, 0xa3, 0x40, 0xeb, 0x50, 0x16, 0xc5, 0x56, 0x2d, 0x14,
	0x9f, 0x68, 0x0f, 0xaa, 0xd7, 0xee, 0x38, 0x36, 0x70, 0xdc, 0xca, 0xbc, 0x1b, 0xd5, 0x63, 0xc6,
	0x08, 0x77, 0x94, 0xd4, 0x8b, 0xd2, 0x73, 0xab, 0xf3, 0x0d, 0x6c, 0x2f, 0x8d, 0x64, 0x81, 0x87,
	0xcd, 0xbc, 0x07, 0x3b, 0x67, 0x08, 0xff, 0x59, 0x86, 0xaa, 0xb4, 0x8e, 0x3a, 0x50, 0xf3, 0x5c,
	0x4e, 0x46, 0x11, 0x35, 0xaa, 0x29, 0x8d, 0x1e, 0xc0, 0x0a, 0x9b, 0x4d, 0x86, 0xd1, 0x58, 0x1b,
	0xd0, 0x94, 0x00, 0x48, 0x48, 0xf8, 0x8f, 0x11, 0xbd, 0xd2, 0xe8, 0x32, 0x64, 0xe6, 0xb1, 0xa2,
	0x20, 0x29, 0x09, 0x11, 0xd9, 0x3b, 0x62, 0xc0, 0x24, 0x3e, 0x33, 0xe8, 0xae, 0xe4, 0xa1, 0xfb,
	0x39, 0x6c, 0xa5, 0xc8, 0x61, 0x24, 0xf4, 0x49, 0x76, 0xbd, 0x56, 0xa5, 0x9f, 0xfb, 0xe6, 0xf8,
	0x7b, 0x79, 0x6a, 0x10, 0xf7, 0x02, 0xb6, 0x53, 0x3d, 0x4a, 0xbc, 0x80, 0x5c, 0xe7, 0x34, 0x6b,
	0x52, 0x33, 0x35, 0xec, 0xe8, 0xf3, 0xe5, 0x68, 0xb5, 0x17, 0xa1, 0xb5, 0x07, 0xa9, 0xef, 0x22,
	0x62, 0x41, 0x4a, 0x6f, 0x98, 0xc3, 0x3c, 0x6a, 0x77, 0xa1, 0x29, 0x28, 0xe2, 0x0f, 0xdc, 0x89,
	0x40, 0x53, 0xbb, 0x2e, 0x65, 0x1b, 0x8a, 0x79, 0x2c, 0x79, 0xe8, 0x09, 0xb4, 0x28, 0xf1, 0x09,
	0x99, 0x64, 0x62, 0x0d, 0x29, 0xb6, 0x66, 0xd8, 0x4a, 0x10, 0xff, 0x52, 0x82, 0x52, 0x3f, 0x11,
	0xf1, 0x7e, 0x50, 0x1a, 0xd5, 0xb5, 0x26, 0x2b, 0x94, 0x64, 0x17, 0x34, 0x63, 0x30, 0x8d, 0x87,
	0x02, 0x16, 0xaa, 0x83, 0x0d, 0xc5, 0xbc, 0x90, 0x3c, 0xf4, 0x14, 0xd6, 0xe7, 0xca, 0xa5, 0x1a,
	0xda, 0xa2, 0x73, 0x65, 0xaa, 0xba, 0x02, 0x2f, 0xb2, 0xb1, 0xf5, 0x5e, 0x2b, 0x77, 0x55, 0x14,
	0x48, 0xe5, 0xa9, 0x40, 0xc6, 0x84, 0x30, 0xe6, 0x8e, 0x54, 0xb7, 0x6d, 0xc7, 0x90, 0x08, 0x41,
	0x85, 0x05, 0xa3, 0x50, 0xbf, 0x18, 0xf2, 0x5b, 0xf0, 0xf8, 0x6c, 0x4a, 0x74, 0x73, 0xe5, 0xb7,
	0xc4, 0x1c, 0x77, 0x79, 0x6c, 0x1a, 0xa7, 0x29, 0x21, 0xeb, 0xbb, 0xdc, 0x95, 0xdd, 0xb1, 0x1d,
	0xf9, 0x8d, 0x9f, 0x82, 0xdd, 0x4f, 0xcc, 0xab, 0xfa, 0x08, 0x4a, 0x3c, 0x91, 0xc5, 0xa8, 0xf7,
	0x1a, 0xb9, 0xa7, 0x3d, 0x71, 0x4a, 0x3c, 0xc1, 0x3f, 0x5b, 0x00, 0x42, 0x56, 0x3f, 0xaa, 0x1b,
	0x50, 0xe5, 0xc9, 0x20, 0xf0, 0x75, 0xf1, 0x2a, 0x3c, 0x79, 0xed, 0x8b, 0xe0, 0xa7, 0x24, 0xf4,
	0x83, 0x70, 0xa4, 0x87, 0x94, 0x21, 0x45, 0x50, 0xef, 0x63, 0x12, 0x13, 0x5f, 0x96, 0xa7, 0xec,
	0x68, 0x2a, 0x17, 0x6c, 0xa5, 0x10, 0xec, 0xd2, 0x32, 0xe0, 0xaf, 0xe0, 0x41, 0xfa, 0xb6, 0x8c,
	0x02, 0xc6, 0x09, 0x35, 0xf1, 0xcf, 0x75, 0xcc, 0x9a, 0xef, 0x18, 0xfe, 0x18, 0x5a, 0xfd, 0xe4,
	0x94, 0x70, 0x37, 0x18, 0x1b, 0xbd, 0x45, 0xa9, 0xe0, 0x5f, 0x2d, 0x58, 0xcf, 0x04, 0x6f, 0x4a,
	0x5a, 0x95, 0xad, 0xb4, 0xb8, 0x6c, 0xe8, 0x10, 0xc0, 0xa3, 0xc4, 0xe5, 0x41, 0x14, 0x9e, 0xaa,
	0x51, 0xb2, 0x64, 0x6e, 0xe6, 0xc4, 0xd0, 0x36, 0xd4, 0xd4, 0x15, 0x09, 0x7c, 0xfd, 0x0e, 0xac,
	0x4a, 0xfa, 0xb5, 0x8f, 0x7f, 0xb3, 0xa0, 0xde, 0xa7, 0x6e, 0xc8, 0x5c, 0x4f, 0x08, 0x23, 0x0c,
	0x3a, 0xbf, 0x5c, 0xce, 0x0d, 0xa7, 0xc0, 0x43, 0x8f, 0xc0, 0x16, 0x68, 0x71, 0x79, 0x4c, 0xcd,
	0x4b, 0x96, 0x31, 0xd0, 0xff, 0x01, 0x28, 0xf1, 0x8a, 0xe8, 0xcd, 0x71, 0x6e, 0x09, 0x5c, 0x7c,
	0x04, 0x28, 0x17, 0x97, 0xa9, 0xed, 0x63, 0x71, 0xe5, 0x34, 0xa6, 0xee, 0xe7, 0xd2, 0xce, 0x49,
	0x96, 0xfa, 0x09, 0xe6, 0xb0, 0x51, 0x50, 0xfe, 0x4f, 0x40, 0x86, 0x0f, 0x60, 0xa3, 0x9f, 0xb0,
	0x93, 0x99, 0xbe, 0xa2, 0xff, 0xbc, 0x5d, 0x1c, 0x41, 0xbd, 0x9f, 0xb0, 0x34, 0xbc, 0x4f, 0xa0,
	0x2c, 0xd6, 0x1b, 0x4b, 0xce, 0xbe, 0x4e, 0xbe, 0xf5, 0x45, 0xdc, 0x38, 0x42, 0x0c, 0x7f, 0x07,
	0x0f, 0x95, 0x37, 0x51, 0xae, 0xe3, 0xd0, 0xbf, 0xad, 0x57, 0xf1, 0xd4, 0xab, 0x06, 0xe8, 0x21,
	0xa4, 0xea, 0x7d, 0x2a, 0x80, 0xfc, 0x76, 0xea, 0xbb, 0x9c, 0xdc, 0x04, 0xe4, 0x9b, 0xe1, 0x89,
	0x99, 0x40, 0xb9, 0xb1, 0xa2, 0xd3, 0xca, 0xca, 0x25, 0xec, 0xd4, 0xd2, 0x3b, 0x99, 0x9a, 0x2f,
	0xcd, 0x99, 0x2f, 0x2f, 0x41, 0xff, 0x26, 0x54, 0x09, 0xa5, 0x11, 0xd5, 0x85, 0x57, 0x04, 0xfe,
	0xc9, 0x82, 0x9a, 0x99, 0xd0, 0x37, 0xe4, 0x9d, 0xdb, 0xa2, 0x4a, 0xc5, 0x2d, 0x6a, 0xe1, 0xe6,
	0x53, 0x5e, 0xbc, 0xf9, 0xa4, 0x83, 0xb2, 0x92, 0x1b, 0x94, 0xf8, 0x77, 0x0b, 0x9a, 0x85, 0x25,
	0x01, 0x3d, 0x37, 0x55, 0x56, 0xed, 0xc4, 0x4b, 0x96, 0x09, 0x05, 0x7a, 0xb5, 0xb9, 0x28, 0x85,
	0xce, 0x39, 0x40, 0xc6, 0x5c, 0xb0, 0x44, 0x74, 0x8b, 0x6b, 0x0a, 0x9a, 0xb7, 0x9c, 0x5f, 0x2c,
	0xf4, 0x03, 0x35, 0x26, 0x37, 0xf7, 0x15, 0x7f, 0x26, 0xe4, 0xce, 0xe5, 0x20, 0x9c, 0xdb, 0xfa,
	0xc3, 0x78, 0x32, 0x24, 0xb4, 0xb0, 0xc0, 0xbf, 0x91, 0x2c, 0xfc, 0xb5, 0xe8, 0xb7, 0xd1, 0xba,
	0x13, 0x8c, 0xa5, 0x5f, 0x47, 0x4e, 0xd6, 0x7f, 0xeb, 0xd7, 0x68, 0xdd, 0xc9, 0xef, 0x97, 0xb0,
	0x25, 0xaf, 0xcf, 0xdd, 0xfe, 0x76, 0x10, 0xac, 0x9f, 0x1b, 0x60, 0x68, 0xb5, 0x93, 0x3d, 0xb8,
	0xe7, 0x45, 0x93, 0xfd, 0x4b, 0x42, 0xfd, 0x20, 0x66, 0xca, 0xff, 0x49, 0xe3, 0x95, 0x22, 0x2f,
	0x04, 0x75, 0x61, 0xfd, 0x90, 0xfe, 0xa6, 0x0d, 0x57, 0xe4, 0xd7, 0xe1, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xae, 0x8e, 0x20, 0x74, 0xd5, 0x0d, 0x00, 0x00,
}
